#!/bin/bash

username="azureuser"
password="bogdan_tailup_sgx_thesis@2023"
location="westus"

resourceGroup="bogdanTailupThesisFrameworkResourceGroup"

vnetAddressSpace="10.0.0.0/16"
vnetName="bogdanTailupThesisFrameworkVnet"

subnetAddressSpace="10.0.0.0/24"
subnetName="bogdanTailupThesisFrameworkSubnet"

publicIpName="bogdanTailupThesisFrameworkIP"
publicIpAllocationMethod="Static"
publicIpSku="Basic"
publicIpVersion="IPv4"

networkSecurityGroupName="bogdanTailupThesisFrameworkNSG"

networkSecurityRuleInbound="bogdanTailupThesisFrameworkInboundRule"
networkSecurityRuleInboundAccess="Allow"
networkSecurityRuleInboundDirection="Inbound"
networkSecurityRuleInboundPriority="100"
networkSecurityRuleInboundSourceAddressPrefixes="[*]"
networkSecurityRuleInboundSourcePortRanges="[*]"
networkSecurityRuleInboundDestinationAddressPrefixes="[*]"
networkSecurityRuleInboundDestinationPortRanges="[*]"
networkSecurityRuleInboundProtocol="Tcp"


networkSecurityRuleOutbound="bogdanTailupThesisFrameworkOutboundRule"
networkSecurityRuleOutboundAccess="Allow"
networkSecurityRuleOutboundDirection="Outbound"
networkSecurityRuleOutboundPriority="100"
networkSecurityRuleOutboundSourceAddressPrefixes="[*]"
networkSecurityRuleOutboundSourcePortRanges="[*]"
networkSecurityRuleOutboundDestinationAddressPrefixes="[*]"
networkSecurityRuleOutboundDestinationPortRanges="[*]"
networkSecurityRuleOutboundProtocol="Tcp"

networkInterfaceName="bogdanTailupThesisFrameworkNetworkInterface"

vmname="bogdanTailupThesisFrameworkVM"
vmImage="debian"
vmSku="Standard"
virtualMachineSize="Standard_DS2_v2"